import Head from "next/head";
import Header from "./components/Header";
import { Button } from "@mui/material";
import { StatusPage, StatusPageConfig } from "react-healthy";

export default function Admin() {
  const statusPageConfig = {
    apis: [
      {
        name: "User API",
        endpoint: "/api/users",
      },
      {
        name: "Product API",
        endpoint: "/api/products",
      },
    ],
  };

  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="status">
        <StatusPage config={statusPageConfig} />
      </div>
    </>
  );
}
