import Head from "next/head";
import Header from "./components/header";
import { Button } from "@mui/material";
export default function Admin() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="form" align="center">
        <h1 className="mainText">Admin Login</h1>
        <form>
          <label className="labels">
            Username:
            <input type="text" className="inputs" name="username" />
          </label>
          <label className="labels">
            Password:
            <input type="text" className="inputs" name="password" />
          </label>
          <button className="submitButtonAdmin" onClick={"submit"}>
            Submit
          </button>
        </form>
      </div>
    </>
  );
}
