import Head from "next/head";
import { Inter } from "@next/font/google";
import { Montserrat } from "@next/font/google";
import Header from "./components/header";
import * as React from "react";
import PostButton from "./components/postButton";

const maintenance = false;

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  if (maintenance) {
    return (
      <>
        <div className="maintenance">
          <h1>Be Right Back.</h1>
        </div>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className="postButton">
          <PostButton />
        </div>
      </>
    );
  }
}
